# Generated by Django 4.1.6 on 2023-03-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comidadieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='descripcion',
            field=models.TextField(default=0),
        ),
    ]
